### ISSUE TITLE
Server crash crafting piston v0.1.8

### ISSUE THREAD

**Issue by BinaryConstruct** [Xhamolk/XACT#33]
When crafting 
XACT v0.1.8
Forge minecraftforge-universal-1.4.5-6.4.1.436

Steps to reproduce:
Using craftpad create chip with piston recipe. 
Put chip in first slot of crafter.
Add materials for piston.
create piston -> crash

http://pastebin.com/LF5MhrnY

**Comment by Xhamolk** [comment]
Thank you for the report. Honestly, I'm kind of excited because this is the first issue I receive on github. 

But now, down to business:
It seems that TileEntity.getWorldObj() is not defined for the server... oh well. I'll fix it. 

Leaving this open until I push another build.

**Comment by BinaryConstruct** [comment]
The least I could do to help :+1:
