### ISSUE TITLE
Make NEI show the encoded recipe

### ISSUE THREAD

**Issue by Xhamolk** [Xhamolk/XACT#39]
When pressing the "U" key (the usages key) over an encoded chip, make NEI display a custom screen showing the recipe encoded on the chip. 

This is because I'm sure that encoded chips won't play a role as recipe ingredients any time soon.

**Comment by odininon** [comment]
Just sent in a PR that is very basic that does this.

**Comment by Xhamolk** [comment]
Looks good. Need to adjust the chip's coords. 
I might create another background image to display the stuff.

**Comment by Xhamolk** [comment]
Closed via a2e8b31537ca183aafe35d002569329bad119a4d
