### ISSUE TITLE
Ingredient List

### ISSUE THREAD

**Issue by Xhamolk** [Xhamolk/XACT#44]
- need to find a good name for that, as it's a 'crafting project'

Generates an item that lists all the "raw" ingredients.

**Comment by Xhamolk** [comment]
Display the ingredients on the "Plan GUI" 

Show the following details:
- The item's icon
- The item's name.
- The required amount of this item

**Comment by Xhamolk** [comment]
Need to speak with bXi, so I can use his idea: painting the list's contents on the player's HUD.

**Comment by odininon** [comment]
You still want to plaint the contents on the HUD?

**Comment by Xhamolk** [comment]
Yeah, that's planned. But i don't have the time to work on it right now...

**Comment by Xhamolk** [comment]
Closing until I get the time to work on it.
