### ISSUE TITLE
Upcoming MINOR Features

### ISSUE THREAD

**Issue by Xhamolk** [Xhamolk/XACT#54]
Minor:
- [x] 1. CraftPad's tooltip should tell the current recipe.
- [x] 2. Import the recipe on a chip by right clicking on the crafter's main output slot. This is required to get the recipe of one of the ingredients.
- [x] 3. The "clear grid" key should be customizable, but default to the down arrow.
- [ ] 4. the tooltips of the crafter's left slots should not be drawn on top of the grid.
- [x] 5. there needs to be a way to get the last recipe as well.. 
  > When getting the recipes for the crafted ingredients for the Cooling Core (GraviSuite), I had to get the last recipe over and over from NEI. 

Visual: 
- [ ] 6. redo the machine's texture: make it look more natural.
- [ ] 7. perhaps make the item's 32x32 ?

**Comment by Xhamolk** [comment]
As of b236b5e15dd854980b9549baf7282cd1e1440608, the directional keys perform the following actions:

For the Crafter:
- UP key: load the recipe from the hovered Recipe Chip
- DOWN key: clear the crafting grid.
- LEFT key: go to the previous recipe (if any).
- RIGHT key: go to the next recipe (if any),
- BACK key & DELETE key: will clear the list of previous recipes.

For the Craft Pad:
- DOWN key: clear the crafting grid.
  Todo: use the up key to load a chip.

**Comment by odininon** [comment]
Working on 3 right now. Will be putting in a PR shortly.
