### ISSUE TITLE
XACT fails to craft

### ISSUE THREAD

**Issue by target-san** [Xhamolk/XACT#73]
Sometimes I observe following issue:
1. Set recipe from NEI
2. Try to craft device
Observed: crafted item disappears after several seconds, with resources returning back to XACT's inventory. Might happen even after exiting XACT GUI.
Observed: very often; several times observed when setting recipe manually; didn't happen on vanilla items
Items: Thermal Expansion complex machines
XACT version: 0.3.1

**Comment by Xhamolk** [comment]
Please try the latest version. The crafting mechanism has been significantly changed since 0.3.1.

**Comment by Xhamolk** [comment]
Closing this as I can't reproduce.
