### ISSUE TITLE
Allow ad-hoc crafting

### ISSUE THREAD

**Issue by target-san** [Xhamolk/XACT#74]
Sometimes it's not very convenient to craft items by setting shadows and returning items to inventory - requires additional clicks, especially when you need something simple like sticks from planks, or craft single item. Might be an improvement to allow old Workbench/Project Table behavior when items are actually placed on grid.

**Comment by Xhamolk** [comment]
I'll look into having the dual functionality implemented. This might take a while, but I'm certainly interested in having this behavior in my mod.

**Comment by Xhamolk** [comment]
Added to my to-do list.
