### ISSUE TITLE
Multi-step crafting

### ISSUE THREAD

**Issue by Xhamolk** [Xhamolk/XACT#77]
Find the time to do it... add a machine if necessary. 
Most of the framework is already there.

**Comment by odininon** [comment]
You have been wanting to do this for a long time. :+1:

**Comment by Xhamolk** [comment]
**Multi-step Crafting**: 
If the missing ingredients can be crafted from a chip, they should. 

There should be a block that extends the functionality of the Crafter: it enable multi-step crafting.
No additional cost would be necessary.

If this block needs chips for crafting, I might need to add an additional chip storage.

**Chip Expander**:
Store what? how much, etc?

**Comment by Xhamolk** [comment]
Added to my to-do list.
